#! /bin/sh

# Autostart
sxhkd &

# Configs
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           5
bspc config top_padding	20
bspc config pointer_motion_interval	50
bspc config automatic_scheme    spiral

# Colors
bspc config focused_border_color  "#acb0d0"

# Rules
bspc rule -a "*:*:Picture-in-picture"		 state=floating 

# Polybar
$HOME/.config/polybar/launch.sh
