#! /bin/sh
# AutoStart
sxhkd &

# Configs
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           5
bspc config bottom_padding	20

bspc config automatic_scheme    spiral

# Colors
bspc config focused_border_color  "#acb0d0"

# Rules
bspc rule -a "*:*:Picture-in-picture"		 state=floating 

# Multi-Monitor Setup
if [ -x $HOME/bin/bspwm-dual-monitor ];then
    $HOME/bin/bspwm-dual-monitor
fi

# Polybar
$HOME/.config/polybar/launch.sh

