#!/bin/bash

pamixer --list-sources | grep -i kraken >/dev/null
if [ $? == 0 ]; then
	sink=$(pamixer --list-sources | grep  Kraken | grep -v Monitor| awk {'print $1'})
else
	sink=$(pamixer --list-sources | grep "Tiger Lake-LP Smart Sound Technology Audio Controller Headphones Stereo Microphone" | awk \{'print $1'\})
fi

	if $(pamixer --source "$sink" --get-mute); then
		echo ""
	else
		echo ""
	fi
